name: first workflow

on: push

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: run Action sample
        run : echo "This workflow runs successfully"
        
      - name: Simulating error in github action 
        run: echo "Simulating error in github action"; exit 1
